# Generated by Django 5.2.9 on 2025-12-28 15:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('setup', 'Setup'), ('captains_assigned', 'Captains Assigned'), ('participants_assigned', 'Participants Assigned'), ('finalized', 'Finalized')], default='setup', max_length=30)),
                ('event_date', models.DateField(blank=True, help_text='Date of the event (e.g., 2025-11-09)', null=True)),
                ('arrival_time', models.TimeField(blank=True, help_text='Time guests should arrive (e.g., 19:00)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_status',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pretix_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('given_name', models.CharField(max_length=255)),
                ('family_name', models.CharField(max_length=255)),
                ('attendee_name', models.CharField(max_length=255)),
                ('attendee_email', models.EmailField(max_length=254)),
                ('is_table_captain', models.BooleanField(default=False)),
                ('captain_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('captain_preferred_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('cancelled', 'Cancelled'), ('late_joiner', 'Late Joiner')], default='registered', max_length=20)),
                ('manual_status_override', models.BooleanField(default=False, help_text='True if status was manually set and should not be overridden by Pretix sync')),
                ('manual_email_override', models.BooleanField(default=False, help_text='True if email was manually changed and should not be overridden by Pretix sync')),
            ],
            options={
                'db_table': 'participants',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('taxi_time', models.PositiveIntegerField(blank=True, help_text='Travel time by taxi in minutes', null=True)),
                ('public_transport_time', models.PositiveIntegerField(blank=True, help_text='Travel time by public transport in minutes', null=True)),
                ('public_transport_lines', models.CharField(blank=True, help_text='Public transport lines/routes', max_length=255, null=True)),
                ('max_seats', models.PositiveIntegerField(help_text='Maximum seating capacity')),
                ('reservation_channel', models.CharField(blank=True, max_length=255, null=True)),
                ('reservation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reservation_confirmed', models.DateTimeField(blank=True, null=True)),
                ('assigned_captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_restaurants', to='core.participant')),
            ],
            options={
                'db_table': 'restaurants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_comments', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.participant')),
            ],
            options={
                'db_table': 'participant_comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['participant'], name='participant_partici_aa26b6_idx'), models.Index(fields=['-created_at'], name='participant_created_4e0c37_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_type', models.CharField(choices=[('initial_assignment', 'Initial Assignment'), ('final_assignment', 'Final Assignment'), ('individual_update', 'Individual Update')], max_length=30)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('body_text', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_by', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='core.participant')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='core.restaurant')),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['participant'], name='email_logs_partici_6a5bfd_idx'), models.Index(fields=['-sent_at'], name='email_logs_sent_at_cde0c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='core.participant')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.restaurant')),
            ],
            options={
                'db_table': 'assignments',
                'indexes': [models.Index(fields=['restaurant'], name='assignments_restaur_ffb79e_idx')],
            },
        ),
        migrations.CreateModel(
            name='RestaurantComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_comments', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.restaurant')),
            ],
            options={
                'db_table': 'restaurant_comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant'], name='restaurant__restaur_fcf44d_idx'), models.Index(fields=['-created_at'], name='restaurant__created_0f523f_idx')],
            },
        ),
    ]
