# Generated by Django 5.2.17 on 2026-08-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('initial_assignment', 'Initial Assignment'), ('final_assignment', 'Final Assignment'), ('individual_update', 'Individual Update'), ('captain_overview', 'Captain Overview')], max_length=30),
        ),
    ]
