# Generated by Django 5.2.17 on 2026-08-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_emaillog_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstatus',
            name='assignment_email_body',
            field=models.TextField(default='Dear participant,\n\nWe\'re excited that you join the {event_name} on {event_date}!\n\nYour assigned restaurant: {restaurant_name}\nAddress: {restaurant_address}\n\nHow to get there:\n{taxi_time}\n{pt_time} {pt_lines}\n\nYour Table Captain: {captain_name}\nContact: {captain_email}{captain_phone}\n{captain_contact}\n\nTable Guests:\n{table_guests}\n\nPlease arrive by {arrival_time} at the restaurant to ensure we can start on\ntime. If you have any questions, please feel free to contact your\nTable Captain directly.\n\nAs noted before: this social is self-paid, hence it is advisable to carry cash.\n\nThe reservation for the table is under the name "{reservation_name}".\n\nWe look forward to a wonderful evening with you!\n\nBest regards,\nYour {event_name} Team', help_text='Body for the participant restaurant assignment email'),
        ),
        migrations.AddField(
            model_name='eventstatus',
            name='assignment_email_subject',
            field=models.CharField(default='Pre-Social - Your Restaurant Assignment', help_text='Subject line for the participant restaurant assignment email', max_length=255),
        ),
        migrations.AddField(
            model_name='eventstatus',
            name='captain_overview_email_body',
            field=models.TextField(default='Hi,\n\nThank you again for taking on the role as Table Captain for {event_name}!\n\nAfter a few adjustments, the participant list is now final and I wanted to share the complete overview of your table with you.\n\n{restaurant_name}\n{restaurant_address}\n\nCaptain: {captain_name} ({captain_email})\n\n{guest_list}\n\nAll guests received their table assignment, so everyone should be aware of the arrangements.\n\nEnjoy the evening!\n\nBest regards,\nYour {event_name} Team', help_text='Body for the table captain guest list email'),
        ),
        migrations.AddField(
            model_name='eventstatus',
            name='captain_overview_email_subject',
            field=models.CharField(default='Final Guest List for the {event_name}!', help_text='Subject line for the table captain guest list email', max_length=255),
        ),
        migrations.AddField(
            model_name='eventstatus',
            name='event_name',
            field=models.CharField(blank=True, default='', help_text='Name of the event, available in email templates as {event_name}', max_length=200),
        ),
    ]
