# Generated by Django 5.2.17 on 2026-08-07 15:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_participant_carpool_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpoolMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=500)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_messages', to='core.restaurant')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_messages', to='core.participant')),
            ],
            options={
                'db_table': 'carpool_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['restaurant'], name='carpool_mes_restaur_bba618_idx')],
            },
        ),
    ]
