# Generated by Django 5.2.17 on 2026-08-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_carpoolmessage_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstatus',
            name='assignment_email_body',
            field=models.TextField(default='Dear participant,\n\nWe\'re excited that you join the {event_name} on {event_date}!\n\nYour assigned restaurant: {restaurant_name}\nAddress: {restaurant_address}\n\nHow to get there:\n{taxi_time}\n{pt_time} {pt_lines}\n\nYour Table Captain: {captain_name}\nContact: {captain_email}{captain_phone}\n{captain_contact}\n\nTable Guests:\n{table_guests}\n\nWant to carpool or share a ride with your table? Coordinate here:\n{carpool_link}\n\nPlease arrive by {arrival_time} at the restaurant to ensure we can start on\ntime. If you have any questions, please feel free to contact your\nTable Captain directly.\n\nAs noted before: this social is self-paid, hence it is advisable to carry cash.\n\nThe reservation for the table is under the name "{reservation_name}".\n\nWe look forward to a wonderful evening with you!\n\nBest regards,\nYour {event_name} Team', help_text='Body for the participant restaurant assignment email'),
        ),
    ]
